#!/usr/bin/env node
// api_parity.mjs - compare implemented Fastify routes against
// spec/current/openapi.yaml paths. Emits docs/execution/api_parity.txt.
// Usage: node tools/api_parity.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const METHODS = ['get', 'post', 'put', 'patch', 'delete'];

// --- implemented routes: app.<method>('<path>') across routes/ + app.ts
const impl = [];
const files = [
  join(ROOT, 'src/server/app.ts'),
  ...readdirSync(join(ROOT, 'src/server/routes'))
    .filter((f) => f.endsWith('.ts'))
    .map((f) => join(ROOT, 'src/server/routes', f)),
];
const routeRe = /\bapp\.(get|post|put|patch|delete)\(\s*'([^']+)'/g;
for (const f of files) {
  const src = readFileSync(f, 'utf8');
  let m;
  while ((m = routeRe.exec(src))) impl.push({ method: m[1].toUpperCase(), path: m[2] });
}

// --- spec paths: "  /x/y:" then "    get:" entries
const spec = [];
let curPath = null;
for (const line of readFileSync(join(ROOT, 'spec/current/openapi.yaml'), 'utf8').split('\n')) {
  const p = line.match(/^  (\/\S+):\s*$/);
  if (p) { curPath = p[1]; continue; }
  if (/^  \S/.test(line)) curPath = null;
  const op = curPath && line.match(/^    (get|post|put|patch|delete):\s*$/);
  if (op) spec.push({ method: op[1].toUpperCase(), path: curPath });
}

const norm = (p) => p.replace(/:([A-Za-z_]+)/g, '{$1}');
const implKeys = new Set(impl.map((r) => `${r.method} ${norm(r.path)}`));
const specKeys = new Set(spec.map((r) => `${r.method} ${norm(r.path)}`));

const specDone = spec.filter((r) => implKeys.has(`${r.method} ${norm(r.path)}`));
const specGap = spec.filter((r) => !implKeys.has(`${r.method} ${norm(r.path)}`));
const implExtra = impl.filter((r) => !specKeys.has(`${r.method} ${norm(r.path)}`));

const fmt = (r) => `${r.method.padEnd(6)} ${r.path}`;
const out = [
  `# API parity — implemented routes vs spec/current/openapi.yaml`,
  `# generated by tools/api_parity.mjs`,
  ``,
  `implemented routes: ${impl.length}`,
  `spec operations:    ${spec.length}`,
  `spec implemented:   ${specDone.length}`,
  `spec not implemented: ${specGap.length}`,
  `implemented but not in spec (v5 additions): ${implExtra.length}`,
  ``,
  `## spec operations not implemented (${specGap.length})`,
  `// intentional divergences:`,
  `//   GET  /stores/{storeId}/exports/{exportId}      -> covered by GET /exports (list carries status) + GET /exports/{exportId}/download`,
  `//   POST /public/{publicToken}/bookings           -> implemented as POST /public/booking-pages/{slug}/submissions (APPROVAL_PENDING)`,
  `//   POST /public/bookings/{publicToken}/checkout  -> not implemented by design: the platform never moves store funds;`,
  `//                                                  public submissions stop at APPROVAL_PENDING and the store settles directly.`,
  ...specGap.map(fmt),
  ``,
  `## implemented routes not in spec (${implExtra.length})`,
  ...implExtra.map(fmt),
  ``,
  `## spec operations implemented (${specDone.length})`,
  ...specDone.map(fmt),
  ``,
];
const dest = join(ROOT, 'docs/execution/api_parity.txt');
writeFileSync(dest, out.join('\n'));
console.log(`wrote ${dest}: ${specDone.length}/${spec.length} spec ops implemented, ${implExtra.length} impl-only routes`);
